#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Localized strings for the 24 material pages (materials/<lang>/<material>/).

Those pages were generated by copying the English page and running a word-level
replacement pass, so a large part of the copy stayed English and a number of
sentences ended up half-translated ("ist ein vielseitiges synthetic rubber",
"es conocido por its exceptional rango de temperatura"). The ZH pages carry the
same problem one step further, with Portuguese headings left over from the
PT -> ZH pass.

MATERIAL_STRINGS maps the canonical English string to its five translations.
PARTIAL_TERMS lets the fixer reconstruct the half-translated variant that is
actually on disk for a given language, so both the fully English and the hybrid
form are matched.

EXTRA_STRINGS holds per-language leftovers that have no English original on the
page (mostly Portuguese headings on the ZH pages).
"""

# Terms the original replacement pass already substituted, as
# (localized, canonical English). Used to derive the on-disk variant.
PARTIAL_TERMS = {
    "de": [("Chemikalienbeständigkeit", "chemical resistance"),
           ("Temperaturbereich", "temperature range"),
           ("weit verbreitet", "widely used"),
           ("ist bekannt für", "is known for"),
           ("ist ein vielseitiges", "is a versatile"),
           ("ist ein synthetisches", "is a synthetic"),
           ("Edelstahl 304", "Stainless Steel 304"),
           ("Edelstahl 316", "Stainless Steel 316"),
           ("Pharmazeutisch", "Pharmaceutical")],
    "es": [("resistencia química", "chemical resistance"),
           ("rango de temperatura", "temperature range"),
           ("ampliamente utilizado", "widely used"),
           ("es conocido por", "is known for"),
           ("es un versátil", "is a versatile"),
           ("es un sintético", "is a synthetic"),
           ("Acero Inoxidable 304", "Stainless Steel 304"),
           ("Acero Inoxidable 316", "Stainless Steel 316"),
           ("Farmacéutico", "Pharmaceutical")],
    "fr": [("résistance chimique", "chemical resistance"),
           ("plage de température", "temperature range"),
           ("largement utilisé", "widely used"),
           ("est connu pour", "is known for"),
           ("est un polyvalent", "is a versatile"),
           ("est un synthétique", "is a synthetic"),
           ("Acier Inoxydable 304", "Stainless Steel 304"),
           ("Acier Inoxydable 316", "Stainless Steel 316"),
           ("Pharmaceutique", "Pharmaceutical")],
    "pt": [("resistência química", "chemical resistance"),
           ("faixa de temperatura", "temperature range"),
           ("amplamente utilizado", "widely used"),
           ("é conhecido por", "is known for"),
           ("é um versátil", "is a versatile"),
           ("é um sintético", "is a synthetic"),
           ("Aço Inoxidável 304", "Stainless Steel 304"),
           ("Aço Inoxidável 316", "Stainless Steel 316"),
           ("Farmacêutico", "Pharmaceutical")],
    # The PT -> ZH pass translated a few terms and left the rest Portuguese, so
    # the ZH variants mix Chinese, English and Portuguese in one sentence.
    "zh": [("化学品耐受性", "chemical resistance"),
           ("amplamente utilizado", "widely used"),
           ("faixa de temperatura", "temperature range"),
           ("304不锈钢", "Stainless Steel 304"),
           ("316不锈钢", "Stainless Steel 316")],
}


MATERIAL_STRINGS = {
# ---------------------------------------------------------------- lead copy
"Polyoxymethylene (Acetal) is an engineering plastic with high stiffness and low friction. Used in valves, pumps, and precision parts.": {
 "de": "Polyoxymethylen (Acetal) ist ein technischer Kunststoff mit hoher Steifigkeit und geringer Reibung. Verwendet in Ventilen, Pumpen und Präzisionsteilen.",
 "es": "El polioximetileno (acetal) es un plástico de ingeniería de alta rigidez y baja fricción. Se utiliza en válvulas, bombas y piezas de precisión.",
 "fr": "Le polyoxyméthylène (acétal) est un plastique technique à haute rigidité et faible frottement. Utilisé dans les vannes, les pompes et les pièces de précision.",
 "pt": "O polioximetileno (acetal) é um plástico de engenharia com elevada rigidez e baixo atrito. Utilizado em válvulas, bombas e peças de precisão.",
 "zh": "聚甲醛（Acetal）是一种刚性高、摩擦系数低的工程塑料，常用于阀门、泵和精密零件。"},

"Aluminium is a lightweight metal with good corrosion resistance. It's commonly used in chemical processing equipment, tanks, and heat exchangers.": {
 "de": "Aluminium ist ein leichtes Metall mit guter Korrosionsbeständigkeit. Es wird häufig in Anlagen der chemischen Verfahrenstechnik, in Tanks und Wärmetauschern eingesetzt.",
 "es": "El aluminio es un metal ligero con buena resistencia a la corrosión. Se utiliza habitualmente en equipos de proceso químico, tanques e intercambiadores de calor.",
 "fr": "L'aluminium est un métal léger doté d'une bonne résistance à la corrosion. Il est couramment utilisé dans les équipements de procédés chimiques, les cuves et les échangeurs de chaleur.",
 "pt": "O alumínio é um metal leve com boa resistência à corrosão. É habitualmente utilizado em equipamentos de processos químicos, tanques e permutadores de calor.",
 "zh": "铝是一种耐腐蚀性良好的轻质金属，常用于化工设备、储罐和换热器。"},

"ECTFE and ETFE are fluoropolymers with excellent chemical resistance and high temperature stability. Used in chemical processing and semiconductor industries.": {
 "de": "ECTFE und ETFE sind Fluorpolymere mit ausgezeichneter Chemikalienbeständigkeit und hoher Temperaturstabilität. Eingesetzt in der chemischen Verfahrenstechnik und der Halbleiterindustrie.",
 "es": "El ECTFE y el ETFE son fluoropolímeros con excelente resistencia química y alta estabilidad térmica. Se utilizan en la industria de procesos químicos y de semiconductores.",
 "fr": "L'ECTFE et l'ETFE sont des fluoropolymères offrant une excellente résistance chimique et une grande stabilité thermique. Utilisés dans les procédés chimiques et l'industrie des semi-conducteurs.",
 "pt": "O ECTFE e o ETFE são fluoropolímeros com excelente resistência química e elevada estabilidade térmica. Utilizados em processos químicos e na indústria de semicondutores.",
 "zh": "ECTFE 和 ETFE 是化学品耐受性优秀、耐高温性能突出的氟聚合物，常用于化工工艺和半导体行业。"},

"EPDM (Ethylene Propylene Diene Monomer) is a versatile synthetic rubber excellent for water, steam, and polar chemicals. It's the go-to choice for outdoor applications and hot water systems.": {
 "de": "EPDM (Ethylen-Propylen-Dien-Kautschuk) ist ein vielseitiger Synthesekautschuk, der sich hervorragend für Wasser, Dampf und polare Chemikalien eignet. Er ist die erste Wahl für Außenanwendungen und Warmwassersysteme.",
 "es": "El EPDM (monómero de etileno-propileno-dieno) es un caucho sintético versátil, excelente para agua, vapor y productos químicos polares. Es la opción de referencia para aplicaciones a la intemperie y sistemas de agua caliente.",
 "fr": "L'EPDM (monomère éthylène-propylène-diène) est un caoutchouc synthétique polyvalent, excellent pour l'eau, la vapeur et les produits chimiques polaires. C'est le choix de référence pour les applications extérieures et les circuits d'eau chaude.",
 "pt": "O EPDM (monómero de etileno-propileno-dieno) é uma borracha sintética versátil, excelente para água, vapor e produtos químicos polares. É a escolha de referência para aplicações no exterior e sistemas de água quente.",
 "zh": "EPDM（三元乙丙橡胶）是一种用途广泛的合成橡胶，对水、蒸汽和极性化学品耐受性优异，是户外应用和热水系统的首选材料。"},

"FEP (Fluorinated Ethylene Propylene) is a fluoropolymer with outstanding chemical resistance. Similar to PTFE but with better clarity and weldability.": {
 "de": "FEP (Fluorethylenpropylen) ist ein Fluorpolymer mit herausragender Chemikalienbeständigkeit. Ähnlich wie PTFE, jedoch mit besserer Transparenz und Schweißbarkeit.",
 "es": "El FEP (etileno propileno fluorado) es un fluoropolímero con una resistencia química excepcional. Similar al PTFE, pero con mejor transparencia y soldabilidad.",
 "fr": "Le FEP (éthylène propylène fluoré) est un fluoropolymère offrant une résistance chimique exceptionnelle. Semblable au PTFE, mais avec une meilleure transparence et soudabilité.",
 "pt": "O FEP (etileno propileno fluorado) é um fluoropolímero com resistência química excecional. Semelhante ao PTFE, mas com melhor transparência e soldabilidade.",
 "zh": "FEP（氟化乙烯丙烯共聚物）是一种化学品耐受性极为出色的氟聚合物，性能与 PTFE 相近，但透明度和可焊接性更好。"},

"Low-Density Polyethylene (LDPE) is a flexible plastic with good chemical resistance. Commonly used for squeeze bottles, tubing, and flexible containers.": {
 "de": "Polyethylen niedriger Dichte (LDPE) ist ein flexibler Kunststoff mit guter Chemikalienbeständigkeit. Wird häufig für Quetschflaschen, Schläuche und flexible Behälter verwendet.",
 "es": "El polietileno de baja densidad (LDPE) es un plástico flexible con buena resistencia química. Se usa habitualmente en frascos dosificadores, tubos y envases flexibles.",
 "fr": "Le polyéthylène basse densité (LDPE) est un plastique souple offrant une bonne résistance chimique. Couramment utilisé pour les flacons souples, les tubes et les récipients flexibles.",
 "pt": "O polietileno de baixa densidade (LDPE) é um plástico flexível com boa resistência química. Usado habitualmente em frascos de compressão, tubos e recipientes flexíveis.",
 "zh": "低密度聚乙烯（LDPE）是一种化学品耐受性良好的柔性塑料，常用于挤压瓶、软管和柔性容器。"},

"NBR (Nitrile Butadiene Rubber) is the industry standard for oil and fuel resistance. Also known as Buna-N, it's the most widely used elastomer for hydraulic seals, O-rings, and fuel system components.": {
 "de": "NBR (Nitril-Butadien-Kautschuk) ist der Industriestandard für Öl- und Kraftstoffbeständigkeit. Auch als Buna-N bekannt, ist er das am weitesten verbreitete Elastomer für Hydraulikdichtungen, O-Ringe und Kraftstoffsystemkomponenten.",
 "es": "El NBR (caucho de nitrilo-butadieno) es el estándar del sector para la resistencia a aceites y combustibles. También conocido como Buna-N, es el elastómero más utilizado en juntas hidráulicas, juntas tóricas y componentes de sistemas de combustible.",
 "fr": "Le NBR (caoutchouc nitrile-butadiène) est la référence du secteur pour la résistance aux huiles et aux carburants. Également appelé Buna-N, c'est l'élastomère le plus utilisé pour les joints hydrauliques, les joints toriques et les composants de circuits de carburant.",
 "pt": "O NBR (borracha de nitrilo-butadieno) é o padrão da indústria para resistência a óleos e combustíveis. Também conhecido como Buna-N, é o elastómero mais utilizado em vedantes hidráulicos, anéis O-ring e componentes de sistemas de combustível.",
 "zh": "NBR（丁腈橡胶）是耐油、耐燃油性能的行业标准材料。它又称丁腈胶（Buna-N），是液压密封件、O 形圈和燃油系统部件中应用最广泛的弹性体。"},

"Polyamide (Nylon) offers good mechanical strength and chemical resistance. Used in fittings, gears, and structural components in chemical applications.": {
 "de": "Polyamid (Nylon) bietet gute mechanische Festigkeit und Chemikalienbeständigkeit. Verwendet für Fittings, Zahnräder und Strukturbauteile in chemischen Anwendungen.",
 "es": "La poliamida (nylon) ofrece buena resistencia mecánica y química. Se utiliza en racores, engranajes y componentes estructurales en aplicaciones químicas.",
 "fr": "Le polyamide (nylon) offre une bonne résistance mécanique et chimique. Utilisé pour les raccords, les engrenages et les pièces structurelles dans les applications chimiques.",
 "pt": "A poliamida (nylon) oferece boa resistência mecânica e química. Utilizada em uniões, engrenagens e componentes estruturais em aplicações químicas.",
 "zh": "聚酰胺（尼龙）具有良好的机械强度和化学品耐受性，常用于化工应用中的接头、齿轮和结构件。"},

"PETG is a glycol-modified polyester with good chemical resistance and clarity. Common in food packaging and medical devices.": {
 "de": "PETG ist ein glykolmodifizierter Polyester mit guter Chemikalienbeständigkeit und Transparenz. Verbreitet in Lebensmittelverpackungen und Medizinprodukten.",
 "es": "El PETG es un poliéster modificado con glicol, con buena resistencia química y transparencia. Habitual en envases alimentarios y productos sanitarios.",
 "fr": "Le PETG est un polyester modifié au glycol offrant une bonne résistance chimique et une bonne transparence. Courant dans l'emballage alimentaire et les dispositifs médicaux.",
 "pt": "O PETG é um poliéster modificado com glicol, com boa resistência química e transparência. Comum em embalagens alimentares e dispositivos médicos.",
 "zh": "PETG 是一种乙二醇改性聚酯，化学品耐受性良好且透明度高，常见于食品包装和医疗器械。"},

"Polymethylpentene (PMP) is a transparent plastic with excellent chemical resistance. Used in laboratory equipment and measuring devices.": {
 "de": "Polymethylpenten (PMP) ist ein transparenter Kunststoff mit ausgezeichneter Chemikalienbeständigkeit. Verwendet in Laborgeräten und Messmitteln.",
 "es": "El polimetilpenteno (PMP) es un plástico transparente con excelente resistencia química. Se utiliza en equipos de laboratorio e instrumentos de medida.",
 "fr": "Le polyméthylpentène (PMP) est un plastique transparent offrant une excellente résistance chimique. Utilisé dans le matériel de laboratoire et les instruments de mesure.",
 "pt": "O polimetilpenteno (PMP) é um plástico transparente com excelente resistência química. Utilizado em equipamento de laboratório e instrumentos de medição.",
 "zh": "聚甲基戊烯（PMP）是一种化学品耐受性优秀的透明塑料，常用于实验室器皿和量具。"},

"Polycarbonate is a transparent thermoplastic with high impact resistance. Used in safety equipment and laboratory containers.": {
 "de": "Polycarbonat ist ein transparenter Thermoplast mit hoher Schlagzähigkeit. Verwendet in Schutzausrüstung und Laborbehältern.",
 "es": "El policarbonato es un termoplástico transparente con alta resistencia al impacto. Se utiliza en equipos de protección y recipientes de laboratorio.",
 "fr": "Le polycarbonate est un thermoplastique transparent à haute résistance aux chocs. Utilisé dans les équipements de protection et les récipients de laboratoire.",
 "pt": "O policarbonato é um termoplástico transparente com elevada resistência ao impacto. Utilizado em equipamento de proteção e recipientes de laboratório.",
 "zh": "聚碳酸酯是一种抗冲击性能优异的透明热塑性塑料，常用于安全防护装备和实验室容器。"},

"Polystyrene is an economical plastic with limited chemical resistance. Used in disposable labware and packaging.": {
 "de": "Polystyrol ist ein preiswerter Kunststoff mit eingeschränkter Chemikalienbeständigkeit. Verwendet in Einweg-Laborartikeln und Verpackungen.",
 "es": "El poliestireno es un plástico económico con resistencia química limitada. Se utiliza en material de laboratorio desechable y en envases.",
 "fr": "Le polystyrène est un plastique économique à résistance chimique limitée. Utilisé pour le matériel de laboratoire jetable et les emballages.",
 "pt": "O poliestireno é um plástico económico com resistência química limitada. Utilizado em material de laboratório descartável e embalagens.",
 "zh": "聚苯乙烯是一种价格低廉、化学品耐受性有限的塑料，常用于一次性实验器皿和包装。"},

"Polysulfone is a high-performance thermoplastic with excellent chemical resistance at high temperatures. Used in medical and food processing equipment.": {
 "de": "Polysulfon ist ein Hochleistungsthermoplast mit ausgezeichneter Chemikalienbeständigkeit bei hohen Temperaturen. Verwendet in Medizin- und Lebensmittelverarbeitungsgeräten.",
 "es": "La polisulfona es un termoplástico de altas prestaciones con excelente resistencia química a temperaturas elevadas. Se utiliza en equipos médicos y de procesado de alimentos.",
 "fr": "Le polysulfone est un thermoplastique haute performance offrant une excellente résistance chimique à haute température. Utilisé dans les équipements médicaux et agroalimentaires.",
 "pt": "A polissulfona é um termoplástico de elevado desempenho com excelente resistência química a altas temperaturas. Utilizada em equipamento médico e de processamento alimentar.",
 "zh": "聚砜是一种高性能热塑性塑料，在高温下仍具有优秀的化学品耐受性，常用于医疗和食品加工设备。"},

"Flexible PVC contains plasticizers for flexibility. Used in tubing, cable insulation, and protective clothing.": {
 "de": "Weich-PVC enthält Weichmacher für die Flexibilität. Verwendet in Schläuchen, Kabelisolierungen und Schutzkleidung.",
 "es": "El PVC flexible contiene plastificantes que le aportan flexibilidad. Se utiliza en tubos, aislamiento de cables y ropa de protección.",
 "fr": "Le PVC souple contient des plastifiants qui lui confèrent sa souplesse. Utilisé dans les tuyaux, l'isolation de câbles et les vêtements de protection.",
 "pt": "O PVC flexível contém plastificantes que lhe conferem flexibilidade. Utilizado em tubos, isolamento de cabos e vestuário de proteção.",
 "zh": "软质 PVC 通过添加增塑剂获得柔韧性，常用于软管、电缆绝缘层和防护服。"},

"Rigid PVC (unplasticized) offers excellent chemical resistance to acids and bases. Widely used in pipes, tanks, and chemical storage.": {
 "de": "Hart-PVC (weichmacherfrei) bietet ausgezeichnete Chemikalienbeständigkeit gegenüber Säuren und Laugen. Weit verbreitet in Rohren, Tanks und der Chemikalienlagerung.",
 "es": "El PVC rígido (sin plastificantes) ofrece excelente resistencia química frente a ácidos y bases. Muy utilizado en tuberías, tanques y almacenamiento de productos químicos.",
 "fr": "Le PVC rigide (non plastifié) offre une excellente résistance chimique aux acides et aux bases. Très utilisé pour les tuyauteries, les cuves et le stockage de produits chimiques.",
 "pt": "O PVC rígido (não plastificado) oferece excelente resistência química a ácidos e bases. Muito utilizado em tubagens, tanques e armazenamento de produtos químicos.",
 "zh": "硬质 PVC（未增塑）对酸和碱具有优秀的化学品耐受性，广泛用于管道、储罐和化学品储存。"},

"Styrene Acrylonitrile (SAN) is a transparent plastic with better chemical resistance than polystyrene. Used in housewares and packaging.": {
 "de": "Styrol-Acrylnitril (SAN) ist ein transparenter Kunststoff mit besserer Chemikalienbeständigkeit als Polystyrol. Verwendet in Haushaltswaren und Verpackungen.",
 "es": "El estireno-acrilonitrilo (SAN) es un plástico transparente con mejor resistencia química que el poliestireno. Se utiliza en menaje y envases.",
 "fr": "Le styrène-acrylonitrile (SAN) est un plastique transparent offrant une meilleure résistance chimique que le polystyrène. Utilisé dans les articles ménagers et les emballages.",
 "pt": "O estireno-acrilonitrilo (SAN) é um plástico transparente com melhor resistência química do que o poliestireno. Utilizado em utensílios domésticos e embalagens.",
 "zh": "苯乙烯-丙烯腈共聚物（SAN）是一种透明塑料，化学品耐受性优于聚苯乙烯，常用于家居用品和包装。"},

"Silicone rubber (VMQ) is known for its exceptional temperature range and flexibility. It's FDA-compliant for food contact and widely used in medical, food processing, and high-temperature applications. However, it has limited chemical resistance compared to other elastomers.": {
 "de": "Silikonkautschuk (VMQ) ist für seinen außergewöhnlichen Temperaturbereich und seine Flexibilität bekannt. Er ist FDA-konform für den Lebensmittelkontakt und wird häufig in der Medizintechnik, der Lebensmittelverarbeitung und bei Hochtemperaturanwendungen eingesetzt. Seine Chemikalienbeständigkeit ist jedoch im Vergleich zu anderen Elastomeren begrenzt.",
 "es": "El caucho de silicona (VMQ) destaca por su excepcional rango de temperatura y su flexibilidad. Cumple la normativa FDA para contacto con alimentos y se utiliza ampliamente en aplicaciones médicas, de procesado de alimentos y de alta temperatura. No obstante, su resistencia química es limitada en comparación con otros elastómeros.",
 "fr": "Le caoutchouc silicone (VMQ) est reconnu pour sa plage de température exceptionnelle et sa souplesse. Il est conforme FDA pour le contact alimentaire et largement utilisé dans les applications médicales, agroalimentaires et à haute température. Sa résistance chimique reste toutefois limitée par rapport aux autres élastomères.",
 "pt": "A borracha de silicone (VMQ) é conhecida pela sua excecional faixa de temperatura e flexibilidade. Cumpre a norma FDA para contacto alimentar e é amplamente utilizada em aplicações médicas, de processamento alimentar e de alta temperatura. No entanto, a sua resistência química é limitada em comparação com outros elastómeros.",
 "zh": "硅橡胶（VMQ）以其极宽的使用温度范围和柔韧性著称。它符合 FDA 食品接触要求，广泛应用于医疗、食品加工和高温场合。不过，与其他弹性体相比，它的化学品耐受性较为有限。"},

"(VMQ - Vinyl Methyl Silicone) is a synthetic elastomer made from silicon, oxygen, carbon, and hydrogen. It's prized for its biocompatibility, temperature stability, and non-reactive nature in food and medical applications.": {
 "de": "(VMQ – Vinyl-Methyl-Silikon) ist ein synthetisches Elastomer aus Silicium, Sauerstoff, Kohlenstoff und Wasserstoff. Es wird für seine Biokompatibilität, Temperaturstabilität und Reaktionsträgheit in Lebensmittel- und Medizinanwendungen geschätzt.",
 "es": "(VMQ - silicona de vinilo y metilo) es un elastómero sintético formado por silicio, oxígeno, carbono e hidrógeno. Se valora por su biocompatibilidad, su estabilidad térmica y su carácter no reactivo en aplicaciones alimentarias y médicas.",
 "fr": "(VMQ - silicone vinyl-méthyl) est un élastomère synthétique composé de silicium, d'oxygène, de carbone et d'hydrogène. Il est apprécié pour sa biocompatibilité, sa stabilité thermique et son caractère non réactif dans les applications alimentaires et médicales.",
 "pt": "(VMQ - silicone vinil-metilo) é um elastómero sintético composto por silício, oxigénio, carbono e hidrogénio. É valorizado pela sua biocompatibilidade, estabilidade térmica e natureza não reativa em aplicações alimentares e médicas.",
 "zh": "（VMQ — 乙烯基甲基硅橡胶）是一种由硅、氧、碳、氢构成的合成弹性体，因其生物相容性、温度稳定性以及在食品和医疗应用中的化学惰性而备受青睐。"},

'SS 316 (1.4401/1.4404) is the "marine grade" stainless steel with excellent corrosion resistance. The molybdenum content provides superior protection against chlorides and pitting compared to 304.': {
 "de": "SS 316 (1.4401/1.4404) ist der Edelstahl in „Marine-Qualität“ mit ausgezeichneter Korrosionsbeständigkeit. Der Molybdängehalt bietet gegenüber 304 einen deutlich besseren Schutz vor Chloriden und Lochfraß.",
 "es": "El SS 316 (1.4401/1.4404) es el acero inoxidable de «grado marino», con excelente resistencia a la corrosión. Su contenido en molibdeno ofrece una protección muy superior a la del 304 frente a cloruros y picaduras.",
 "fr": "Le SS 316 (1.4401/1.4404) est l'acier inoxydable dit « qualité marine », doté d'une excellente résistance à la corrosion. Sa teneur en molybdène offre une protection nettement supérieure au 304 contre les chlorures et la corrosion par piqûres.",
 "pt": "O SS 316 (1.4401/1.4404) é o aço inoxidável de «grau marítimo», com excelente resistência à corrosão. O teor de molibdénio confere uma proteção muito superior à do 304 contra cloretos e corrosão por picadas.",
 "zh": "SS 316（1.4401/1.4404）是耐腐蚀性优异的“船用级”不锈钢。其钼含量使其在抵抗氯化物和点蚀方面明显优于 304。"},

"Stainless Steel 304 (V2A/1.4301) is the most common stainless steel. Excellent corrosion resistance for general chemical applications.": {
 "de": "Edelstahl 304 (V2A/1.4301) ist der am weitesten verbreitete Edelstahl. Ausgezeichnete Korrosionsbeständigkeit für allgemeine chemische Anwendungen.",
 "es": "El acero inoxidable 304 (V2A/1.4301) es el acero inoxidable más común. Excelente resistencia a la corrosión para aplicaciones químicas generales.",
 "fr": "L'acier inoxydable 304 (V2A/1.4301) est l'acier inoxydable le plus répandu. Excellente résistance à la corrosion pour les applications chimiques courantes.",
 "pt": "O aço inoxidável 304 (V2A/1.4301) é o aço inoxidável mais comum. Excelente resistência à corrosão para aplicações químicas gerais.",
 "zh": "304 不锈钢（V2A/1.4301）是最常见的不锈钢牌号，对一般化工应用具有优异的耐腐蚀性。"},

"Viton® is DuPont's brand name for FPM/FKM fluoroelastomer — the premium choice for seals and gaskets in demanding chemical environments. It offers exceptional resistance to fuels, oils, acids, and solvents, with excellent high-temperature performance up to 200°C.": {
 "de": "Viton® ist der Markenname von DuPont für FPM/FKM-Fluorelastomer – die Premiumwahl für Dichtungen in anspruchsvollen chemischen Umgebungen. Es bietet außergewöhnliche Beständigkeit gegen Kraftstoffe, Öle, Säuren und Lösemittel sowie ausgezeichnete Hochtemperatureigenschaften bis 200 °C.",
 "es": "Viton® es la marca de DuPont para el fluoroelastómero FPM/FKM, la opción premium para juntas y sellos en entornos químicos exigentes. Ofrece una resistencia excepcional a combustibles, aceites, ácidos y disolventes, con un excelente comportamiento a alta temperatura hasta 200 °C.",
 "fr": "Viton® est la marque de DuPont pour le fluoroélastomère FPM/FKM — le choix haut de gamme pour les joints et garnitures en environnement chimique exigeant. Il offre une résistance exceptionnelle aux carburants, huiles, acides et solvants, avec d'excellentes performances à haute température jusqu'à 200 °C.",
 "pt": "Viton® é a marca da DuPont para o fluoroelastómero FPM/FKM — a escolha premium para vedantes e juntas em ambientes químicos exigentes. Oferece resistência excecional a combustíveis, óleos, ácidos e solventes, com excelente desempenho a alta temperatura até 200 °C.",
 "zh": "Viton® 是杜邦公司 FPM/FKM 氟弹性体的品牌名称，是苛刻化学环境中密封件和垫片的高端首选。它对燃油、油类、酸和溶剂具有极为出色的耐受性，并可在高达 200°C 的高温下保持优异性能。"},

"is a registered trademark of The Chemours Company (formerly DuPont) for a family of fluoroelastomers. The generic names are FPM (Europe) and FKM (USA). It's one of the most chemically resistant elastomers available, making it the premium choice for seals, O-rings, and gaskets in demanding applications.": {
 "de": "ist eine eingetragene Marke der Chemours Company (ehemals DuPont) für eine Familie von Fluorelastomeren. Die Gattungsbezeichnungen lauten FPM (Europa) und FKM (USA). Es ist eines der chemikalienbeständigsten verfügbaren Elastomere und damit die Premiumwahl für Dichtungen, O-Ringe und Flachdichtungen in anspruchsvollen Anwendungen.",
 "es": "es una marca registrada de The Chemours Company (antes DuPont) para una familia de fluoroelastómeros. Las denominaciones genéricas son FPM (Europa) y FKM (EE. UU.). Es uno de los elastómeros más resistentes químicamente que existen, lo que lo convierte en la opción premium para sellos, juntas tóricas y juntas en aplicaciones exigentes.",
 "fr": "est une marque déposée de The Chemours Company (anciennement DuPont) désignant une famille de fluoroélastomères. Les appellations génériques sont FPM (Europe) et FKM (États-Unis). C'est l'un des élastomères les plus résistants chimiquement, ce qui en fait le choix haut de gamme pour les joints, joints toriques et garnitures dans les applications exigeantes.",
 "pt": "é uma marca registada da The Chemours Company (anteriormente DuPont) para uma família de fluoroelastómeros. As designações genéricas são FPM (Europa) e FKM (EUA). É um dos elastómeros quimicamente mais resistentes disponíveis, o que o torna a escolha premium para vedantes, anéis O-ring e juntas em aplicações exigentes.",
 "zh": "是科慕公司（原杜邦）旗下一系列氟弹性体的注册商标。其通用名称为 FPM（欧洲）和 FKM（美国）。它是目前化学耐受性最强的弹性体之一，因而成为苛刻工况下密封件、O 形圈和垫片的高端首选。"},

# ---------------------------------------------------- headings and comparisons
"Stainless Steel 316 Chemical Resistance": {
 "de": "Edelstahl 316 Chemikalienbeständigkeit",
 "es": "Resistencia química del acero inoxidable 316",
 "fr": "Résistance chimique de l'acier inoxydable 316",
 "pt": "Resistência química do aço inoxidável 316",
 "zh": "316 不锈钢化学品耐受性"},

"wins on temperature range and food safety but loses on chemical resistance.": {
 "de": "punktet beim Temperaturbereich und bei der Lebensmittelsicherheit, verliert aber bei der Chemikalienbeständigkeit.",
 "es": "gana en rango de temperatura y seguridad alimentaria, pero pierde en resistencia química.",
 "fr": "l'emporte sur la plage de température et la sécurité alimentaire, mais perd sur la résistance chimique.",
 "pt": "ganha em faixa de temperatura e segurança alimentar, mas perde em resistência química.",
 "zh": "在温度范围和食品安全性方面占优，但化学品耐受性较差。"},

"handles fuels and oils but costs more and isn't food-safe.": {
 "de": "kommt mit Kraftstoffen und Ölen zurecht, kostet aber mehr und ist nicht lebensmittelecht.",
 "es": "resiste combustibles y aceites, pero es más caro y no es apto para alimentos.",
 "fr": "supporte les carburants et les huiles, mais coûte plus cher et n'est pas apte au contact alimentaire.",
 "pt": "resiste a combustíveis e óleos, mas é mais caro e não é adequado para contacto alimentar.",
 "zh": "可耐受燃油和油类，但成本更高且不适用于食品接触。"},

"excels with water and steam but can't match silicone's temperature range.": {
 "de": "überzeugt bei Wasser und Dampf, erreicht aber nicht den Temperaturbereich von Silikon.",
 "es": "destaca con agua y vapor, pero no alcanza el rango de temperatura de la silicona.",
 "fr": "excelle avec l'eau et la vapeur, mais n'atteint pas la plage de température du silicone.",
 "pt": "destaca-se com água e vapor, mas não alcança a faixa de temperatura do silicone.",
 "zh": "在水和蒸汽环境中表现出色，但温度范围不及硅橡胶。"},

"excels with fuels, oils, and high temperatures but struggles with ketones and amines.": {
 "de": "überzeugt bei Kraftstoffen, Ölen und hohen Temperaturen, hat aber Schwierigkeiten mit Ketonen und Aminen.",
 "es": "destaca con combustibles, aceites y altas temperaturas, pero tiene problemas con cetonas y aminas.",
 "fr": "excelle avec les carburants, les huiles et les hautes températures, mais peine avec les cétones et les amines.",
 "pt": "destaca-se com combustíveis, óleos e altas temperaturas, mas tem dificuldades com cetonas e aminas.",
 "zh": "在燃油、油类和高温环境中表现出色，但不耐酮类和胺类。"},

"is best for water, steam, and bases but fails with oils and fuels.": {
 "de": "eignet sich am besten für Wasser, Dampf und Laugen, versagt aber bei Ölen und Kraftstoffen.",
 "es": "es la mejor opción para agua, vapor y bases, pero falla con aceites y combustibles.",
 "fr": "convient surtout à l'eau, à la vapeur et aux bases, mais échoue avec les huiles et les carburants.",
 "pt": "é a melhor opção para água, vapor e bases, mas falha com óleos e combustíveis.",
 "zh": "最适合水、蒸汽和碱性介质，但不耐油类和燃油。"},

"handles oils and fuels well but has lower temperature limits and poor ozone resistance.": {
 "de": "kommt gut mit Ölen und Kraftstoffen zurecht, hat aber niedrigere Temperaturgrenzen und eine schlechte Ozonbeständigkeit.",
 "es": "resiste bien aceites y combustibles, pero tiene límites de temperatura más bajos y escasa resistencia al ozono.",
 "fr": "supporte bien les huiles et les carburants, mais présente des limites de température plus basses et une faible résistance à l'ozone.",
 "pt": "lida bem com óleos e combustíveis, mas tem limites de temperatura mais baixos e fraca resistência a ozono.",
 "zh": "对油类和燃油耐受性良好，但耐温上限较低且耐臭氧性较差。"},
}

MATERIAL_STRINGS.update({
# ------------------------------------------------------------ ratings and UI
"Excellent resistance": {"de": "Ausgezeichnete Beständigkeit", "es": "Resistencia excelente",
 "fr": "Résistance excellente", "pt": "Resistência excelente", "zh": "耐受性优秀"},
"Good resistance": {"de": "Gute Beständigkeit", "es": "Buena resistencia",
 "fr": "Bonne résistance", "pt": "Boa resistência", "zh": "耐受性良好"},
"Limited resistance": {"de": "Begrenzte Beständigkeit", "es": "Resistencia limitada",
 "fr": "Résistance limitée", "pt": "Resistência limitada", "zh": "耐受性有限"},
"Excellent (A)": {"de": "Ausgezeichnet (A)", "es": "Excelente (A)", "fr": "Excellent (A)",
 "pt": "Excelente (A)", "zh": "优秀 (A)"},
"Good (B)": {"de": "Gut (B)", "es": "Bueno (B)", "fr": "Bon (B)", "pt": "Bom (B)", "zh": "良好 (B)"},
"Limited (C)": {"de": "Begrenzt (C)", "es": "Limitado (C)", "fr": "Limité (C)",
 "pt": "Aceitável (C)", "zh": "尚可 (C)"},
"Not Recommended (D)": {"de": "Nicht empfohlen (D)", "es": "No recomendado (D)",
 "fr": "Non recommandé (D)", "pt": "Não recomendado (D)", "zh": "不推荐 (D)"},
"A - Excellent": {"de": "A – Ausgezeichnet", "es": "A - Excelente", "fr": "A - Excellent",
 "pt": "A - Excelente", "zh": "A - 优秀"},
"B - Good": {"de": "B – Gut", "es": "B - Bueno", "fr": "B - Bon", "pt": "B - Bom", "zh": "B - 良好"},
"C - Limited": {"de": "C – Begrenzt", "es": "C - Limitado", "fr": "C - Limité",
 "pt": "C - Aceitável", "zh": "C - 尚可"},
"D - Not recommended": {"de": "D – Nicht empfohlen", "es": "D - No recomendado",
 "fr": "D - Non recommandé", "pt": "D - Não recomendado", "zh": "D - 不推荐"},
"A & B (Compatible)": {"de": "A & B (verträglich)", "es": "A y B (compatibles)",
 "fr": "A et B (compatibles)", "pt": "A e B (compatíveis)", "zh": "A 和 B（兼容）"},
"Not Recommended": {"de": "Nicht empfohlen", "es": "No recomendado", "fr": "Non recommandé",
 "pt": "Não recomendado", "zh": "不推荐"},
"Not recommended": {"de": "Nicht empfohlen", "es": "No recomendado", "fr": "Non recommandé",
 "pt": "Não recomendado", "zh": "不推荐"},
"All ratings": {"de": "Alle Bewertungen", "es": "Todas las calificaciones", "fr": "Toutes les notes",
 "pt": "Todas as classificações", "zh": "全部评级"},
"All Ratings": {"de": "Alle Bewertungen", "es": "Todas las calificaciones", "fr": "Toutes les notes",
 "pt": "Todas as classificações", "zh": "全部评级"},
"Ratings:": {"de": "Bewertungen:", "es": "Calificaciones:", "fr": "Notes :",
 "pt": "Classificações:", "zh": "评级："},
"Search chemicals": {"de": "Chemikalien suchen", "es": "Buscar químicos",
 "fr": "Rechercher des produits chimiques", "pt": "Pesquisar produtos químicos", "zh": "搜索化学品"},
"20°C & 50°C data": {"de": "Daten bei 20 °C & 50 °C", "es": "Datos a 20 °C y 50 °C",
 "fr": "Données à 20 °C et 50 °C", "pt": "Dados a 20 °C e 50 °C", "zh": "20°C 与 50°C 数据"},
"1,651+ chemicals tested": {"de": "1.651+ Chemikalien geprüft", "es": "1.651+ químicos probados",
 "fr": "1 651+ produits chimiques testés", "pt": "1.651+ produtos químicos testados",
 "zh": "已测试 1,651+ 种化学品"},
"1,650+ chemicals tested": {"de": "1.650+ Chemikalien geprüft", "es": "1.650+ químicos probados",
 "fr": "1 650+ produits chimiques testés", "pt": "1.650+ produtos químicos testados",
 "zh": "已测试 1,650+ 种化学品"},
"850+ chemicals tested": {"de": "850+ Chemikalien geprüft", "es": "850+ químicos probados",
 "fr": "850+ produits chimiques testés", "pt": "850+ produtos químicos testados",
 "zh": "已测试 850+ 种化学品"},
"Limited data": {"de": "Begrenzte Daten", "es": "Datos limitados", "fr": "Données limitées",
 "pt": "Dados limitados", "zh": "数据有限"},
"Check data": {"de": "Daten prüfen", "es": "Consultar datos", "fr": "Vérifier les données",
 "pt": "Consultar dados", "zh": "查看数据"},
"FDA compliant": {"de": "FDA-konform", "es": "Conforme con la FDA", "fr": "Conforme FDA",
 "pt": "Conforme com a FDA", "zh": "符合 FDA 标准"},
"Oil resistant": {"de": "Ölbeständig", "es": "Resistente a aceites", "fr": "Résistant aux huiles",
 "pt": "Resistente a óleos", "zh": "耐油"},
"Marine grade": {"de": "Marine-Qualität", "es": "Grado marino", "fr": "Qualité marine",
 "pt": "Grau marítimo", "zh": "船用级"},
"Premium elastomer": {"de": "Premium-Elastomer", "es": "Elastómero premium",
 "fr": "Élastomère haut de gamme", "pt": "Elastómero premium", "zh": "高端弹性体"},

# ------------------------------------------------------------ property tables
"Full Name": {"de": "Vollständiger Name", "es": "Nombre completo", "fr": "Nom complet",
 "pt": "Nome completo", "zh": "全称"},
"Also Known As": {"de": "Auch bekannt als", "es": "También conocido como",
 "fr": "Également appelé", "pt": "Também conhecido como", "zh": "别名"},
"Max Temperature": {"de": "Max. Temperatur", "es": "Temperatura máxima",
 "fr": "Température maximale", "pt": "Temperatura máxima", "zh": "最高温度"},
"Min Temperature": {"de": "Min. Temperatur", "es": "Temperatura mínima",
 "fr": "Température minimale", "pt": "Temperatura mínima", "zh": "最低温度"},
"Hardness Range": {"de": "Härtebereich", "es": "Rango de dureza", "fr": "Plage de dureté",
 "pt": "Intervalo de dureza", "zh": "硬度范围"},
"UV/Ozone Resistance": {"de": "UV-/Ozonbeständigkeit", "es": "Resistencia a UV/ozono",
 "fr": "Résistance aux UV/à l'ozone", "pt": "Resistência a UV/ozono", "zh": "耐紫外线/臭氧性"},
"FDA Grades": {"de": "FDA-Qualitäten", "es": "Grados FDA", "fr": "Qualités FDA",
 "pt": "Graus FDA", "zh": "FDA 级别"},
"Oil Resistance": {"de": "Ölbeständigkeit", "es": "Resistencia a aceites",
 "fr": "Résistance aux huiles", "pt": "Resistência a óleos", "zh": "耐油性"},
"Low Carbon Variant": {"de": "Variante mit niedrigem Kohlenstoffgehalt",
 "es": "Variante de bajo carbono", "fr": "Variante à bas carbone",
 "pt": "Variante de baixo carbono", "zh": "低碳型号"},
"Molybdenum Content": {"de": "Molybdängehalt", "es": "Contenido de molibdeno",
 "fr": "Teneur en molybdène", "pt": "Teor de molibdénio", "zh": "钼含量"},
"2-3% (pitting resistance)": {"de": "2–3 % (Lochfraßbeständigkeit)",
 "es": "2-3 % (resistencia a picaduras)", "fr": "2-3 % (résistance aux piqûres)",
 "pt": "2-3 % (resistência a picadas)", "zh": "2-3%（抗点蚀）"},
"No (austenitic)": {"de": "Nein (austenitisch)", "es": "No (austenítico)",
 "fr": "Non (austénitique)", "pt": "Não (austenítico)", "zh": "否（奥氏体）"},
"Yes (use 316L for welding)": {"de": "Ja (für Schweißarbeiten 316L verwenden)",
 "es": "Sí (use 316L para soldadura)", "fr": "Oui (utiliser 316L pour le soudage)",
 "pt": "Sim (usar 316L para soldadura)", "zh": "是（焊接请选用 316L）"},
"Low (most economical)": {"de": "Niedrig (am wirtschaftlichsten)", "es": "Bajo (el más económico)",
 "fr": "Faible (le plus économique)", "pt": "Baixo (o mais económico)", "zh": "低（最经济）"},
"Temperature range:": {"de": "Temperaturbereich:", "es": "Rango de temperatura:",
 "fr": "Plage de température :", "pt": "Faixa de temperatura:", "zh": "温度范围："},
"FDA 21 CFR 177.2600 compliant": {"de": "FDA 21 CFR 177.2600 konform",
 "es": "Conforme con FDA 21 CFR 177.2600", "fr": "Conforme FDA 21 CFR 177.2600",
 "pt": "Conforme com FDA 21 CFR 177.2600", "zh": "符合 FDA 21 CFR 177.2600"},
"USP Class VI biocompatible grades available": {
 "de": "Biokompatible Qualitäten nach USP-Klasse VI verfügbar",
 "es": "Disponibles grados biocompatibles USP Clase VI",
 "fr": "Qualités biocompatibles USP classe VI disponibles",
 "pt": "Disponíveis graus biocompatíveis USP Classe VI",
 "zh": "提供 USP VI 类生物相容性牌号"},

# ---------------------------------------------------------------- application lists
"Hot/cold water seals, plumbing gaskets, water pumps": {
 "de": "Dichtungen für Warm-/Kaltwasser, Sanitärdichtungen, Wasserpumpen",
 "es": "Juntas de agua fría/caliente, juntas de fontanería, bombas de agua",
 "fr": "Joints d'eau chaude/froide, joints de plomberie, pompes à eau",
 "pt": "Vedantes de água quente/fria, juntas de canalização, bombas de água",
 "zh": "冷热水密封件、管路垫片、水泵"},
"Steam hoses, HVAC seals, radiator hoses": {
 "de": "Dampfschläuche, HLK-Dichtungen, Kühlerschläuche",
 "es": "Mangueras de vapor, juntas de climatización, manguitos de radiador",
 "fr": "Flexibles vapeur, joints CVC, durites de radiateur",
 "pt": "Mangueiras de vapor, vedantes de AVAC, mangueiras de radiador",
 "zh": "蒸汽软管、暖通空调密封件、散热器软管"},
"Roofing membranes, window seals, weatherstripping": {
 "de": "Dachbahnen, Fensterdichtungen, Witterungsdichtungen",
 "es": "Membranas de cubierta, juntas de ventana, burletes",
 "fr": "Membranes de toiture, joints de fenêtre, joints d'étanchéité",
 "pt": "Membranas de cobertura, vedantes de janela, borrachas de vedação",
 "zh": "屋面防水卷材、窗户密封条、门窗密封胶条"},
"Fuel hoses, tank seals, gasoline pumps, diesel systems": {
 "de": "Kraftstoffschläuche, Tankdichtungen, Benzinpumpen, Dieselsysteme",
 "es": "Mangueras de combustible, juntas de depósito, bombas de gasolina, sistemas diésel",
 "fr": "Flexibles de carburant, joints de réservoir, pompes à essence, circuits diesel",
 "pt": "Mangueiras de combustível, vedantes de depósito, bombas de gasolina, sistemas a gasóleo",
 "zh": "燃油软管、油箱密封件、汽油泵、柴油系统"},
"Hydraulic seals, O-rings, cylinder seals, pumps": {
 "de": "Hydraulikdichtungen, O-Ringe, Zylinderdichtungen, Pumpen",
 "es": "Juntas hidráulicas, juntas tóricas, juntas de cilindro, bombas",
 "fr": "Joints hydrauliques, joints toriques, joints de vérin, pompes",
 "pt": "Vedantes hidráulicos, anéis O-ring, vedantes de cilindro, bombas",
 "zh": "液压密封件、O 形圈、气缸密封件、泵"},
"Engine seals, transmission seals, oil pan gaskets": {
 "de": "Motordichtungen, Getriebedichtungen, Ölwannendichtungen",
 "es": "Retenes de motor, retenes de transmisión, juntas de cárter",
 "fr": "Joints moteur, joints de transmission, joints de carter d'huile",
 "pt": "Vedantes de motor, vedantes de transmissão, juntas de cárter",
 "zh": "发动机油封、变速箱油封、油底壳垫片"},
"Boat fittings, coastal structures, offshore platforms": {
 "de": "Bootsbeschläge, Küstenbauwerke, Offshore-Plattformen",
 "es": "Herrajes náuticos, estructuras costeras, plataformas offshore",
 "fr": "Accastillage, ouvrages côtiers, plateformes offshore",
 "pt": "Ferragens náuticas, estruturas costeiras, plataformas offshore",
 "zh": "船用配件、沿海结构、海上平台"},
"Process vessels, reactors, cleanroom equipment": {
 "de": "Prozessbehälter, Reaktoren, Reinraumausrüstung",
 "es": "Recipientes de proceso, reactores, equipos de sala limpia",
 "fr": "Cuves de procédé, réacteurs, équipements de salle blanche",
 "pt": "Recipientes de processo, reatores, equipamento de sala limpa",
 "zh": "工艺容器、反应器、洁净室设备"},
"Tanks, conveyors, brewing equipment, dairy": {
 "de": "Tanks, Förderanlagen, Brauereianlagen, Molkereitechnik",
 "es": "Tanques, transportadores, equipos cerveceros, industria láctea",
 "fr": "Cuves, convoyeurs, matériel de brasserie, industrie laitière",
 "pt": "Tanques, transportadores, equipamento cervejeiro, laticínios",
 "zh": "储罐、输送设备、酿造设备、乳品设备"},
"Food processing equipment seals": {
 "de": "Dichtungen für Lebensmittelverarbeitungsanlagen",
 "es": "Juntas para equipos de procesado de alimentos",
 "fr": "Joints pour équipements agroalimentaires",
 "pt": "Vedantes para equipamento de processamento alimentar",
 "zh": "食品加工设备密封件"},
"Medical devices and implants": {"de": "Medizinprodukte und Implantate",
 "es": "Productos sanitarios e implantes", "fr": "Dispositifs médicaux et implants",
 "pt": "Dispositivos médicos e implantes", "zh": "医疗器械与植入物"},
"Baby bottle nipples and kitchen utensils": {"de": "Babyflaschensauger und Küchenutensilien",
 "es": "Tetinas de biberón y utensilios de cocina",
 "fr": "Tétines de biberon et ustensiles de cuisine",
 "pt": "Tetinas de biberão e utensílios de cozinha", "zh": "婴儿奶嘴和厨房用具"},
"High-temperature gaskets (ovens, HVAC)": {"de": "Hochtemperaturdichtungen (Öfen, HLK)",
 "es": "Juntas de alta temperatura (hornos, climatización)",
 "fr": "Joints haute température (fours, CVC)",
 "pt": "Juntas de alta temperatura (fornos, AVAC)", "zh": "高温垫片（烤箱、暖通空调）"},
"Electrical insulation": {"de": "Elektrische Isolierung", "es": "Aislamiento eléctrico",
 "fr": "Isolation électrique", "pt": "Isolamento elétrico", "zh": "电气绝缘"},
"Fuel system seals (automotive, aerospace)": {
 "de": "Dichtungen für Kraftstoffsysteme (Automobil, Luft- und Raumfahrt)",
 "es": "Juntas de sistemas de combustible (automoción, aeroespacial)",
 "fr": "Joints de circuits de carburant (automobile, aéronautique)",
 "pt": "Vedantes de sistemas de combustível (automóvel, aeroespacial)",
 "zh": "燃油系统密封件（汽车、航空航天）"},
"Chemical pump seals and gaskets": {"de": "Dichtungen für Chemiepumpen",
 "es": "Sellos y juntas para bombas químicas", "fr": "Joints et garnitures de pompes chimiques",
 "pt": "Vedantes e juntas de bombas químicas", "zh": "化工泵密封件与垫片"},
"Oil field equipment": {"de": "Ausrüstung für Ölfelder", "es": "Equipos para yacimientos petrolíferos",
 "fr": "Équipements pétroliers", "pt": "Equipamento de campos petrolíferos", "zh": "油田设备"},
"Semiconductor manufacturing": {"de": "Halbleiterfertigung", "es": "Fabricación de semiconductores",
 "fr": "Fabrication de semi-conducteurs", "pt": "Fabrico de semicondutores", "zh": "半导体制造"},
"Pharmaceutical processing": {"de": "Pharmazeutische Verarbeitung", "es": "Procesado farmacéutico",
 "fr": "Transformation pharmaceutique", "pt": "Processamento farmacêutico", "zh": "制药加工"},

# ------------------------------------------------------------- warning lists
"EPDM swells and degrades when exposed to:": {
 "de": "EPDM quillt und zersetzt sich bei Kontakt mit:",
 "es": "El EPDM se hincha y se degrada al exponerse a:",
 "fr": "L'EPDM gonfle et se dégrade au contact de :",
 "pt": "O EPDM incha e degrada-se quando exposto a:",
 "zh": "EPDM 接触以下物质会溶胀并降解："},
"NBR degrades when exposed to:": {"de": "NBR zersetzt sich bei Kontakt mit:",
 "es": "El NBR se degrada al exponerse a:", "fr": "Le NBR se dégrade au contact de :",
 "pt": "O NBR degrada-se quando exposto a:", "zh": "NBR 接触以下物质会降解："},
"SS 316 can corrode when exposed to:": {"de": "SS 316 kann bei Kontakt mit Folgendem korrodieren:",
 "es": "El SS 316 puede corroerse al exponerse a:", "fr": "Le SS 316 peut se corroder au contact de :",
 "pt": "O SS 316 pode corroer quando exposto a:", "zh": "SS 316 接触以下物质可能发生腐蚀："},
"Petroleum oils and fuels (gasoline, diesel)": {"de": "Mineralöle und Kraftstoffe (Benzin, Diesel)",
 "es": "Aceites minerales y combustibles (gasolina, diésel)",
 "fr": "Huiles minérales et carburants (essence, gazole)",
 "pt": "Óleos minerais e combustíveis (gasolina, gasóleo)", "zh": "石油类油品和燃料（汽油、柴油）"},
"Mineral oils and greases": {"de": "Mineralöle und Fette", "es": "Aceites y grasas minerales",
 "fr": "Huiles et graisses minérales", "pt": "Óleos e massas minerais", "zh": "矿物油和润滑脂"},
"Aromatic hydrocarbons (benzene, toluene)": {"de": "Aromatische Kohlenwasserstoffe (Benzol, Toluol)",
 "es": "Hidrocarburos aromáticos (benceno, tolueno)",
 "fr": "Hydrocarbures aromatiques (benzène, toluène)",
 "pt": "Hidrocarbonetos aromáticos (benzeno, tolueno)", "zh": "芳香烃（苯、甲苯）"},
"Halogenated solvents": {"de": "Halogenierte Lösemittel", "es": "Disolventes halogenados",
 "fr": "Solvants halogénés", "pt": "Solventes halogenados", "zh": "卤代溶剂"},
"Concentrated acids": {"de": "Konzentrierte Säuren", "es": "Ácidos concentrados",
 "fr": "Acides concentrés", "pt": "Ácidos concentrados", "zh": "浓酸"},
"Turpentine and hydrocarbon solvents": {"de": "Terpentin und Kohlenwasserstoff-Lösemittel",
 "es": "Trementina y disolventes de hidrocarburos",
 "fr": "Térébenthine et solvants hydrocarbonés",
 "pt": "Terebintina e solventes de hidrocarbonetos", "zh": "松节油和烃类溶剂"},
"Ozone and UV exposure (outdoor use)": {"de": "Ozon- und UV-Einwirkung (Außeneinsatz)",
 "es": "Exposición al ozono y a los rayos UV (uso exterior)",
 "fr": "Exposition à l'ozone et aux UV (usage extérieur)",
 "pt": "Exposição a ozono e UV (utilização no exterior)", "zh": "臭氧和紫外线暴露（户外使用）"},
"Ketones (acetone, MEK)": {"de": "Ketone (Aceton, MEK)", "es": "Cetonas (acetona, MEK)",
 "fr": "Cétones (acétone, MEK)", "pt": "Cetonas (acetona, MEK)", "zh": "酮类（丙酮、丁酮）"},
"Esters and ethers": {"de": "Ester und Ether", "es": "Ésteres y éteres", "fr": "Esters et éthers",
 "pt": "Ésteres e éteres", "zh": "酯类和醚类"},
"Strong acids": {"de": "Starke Säuren", "es": "Ácidos fuertes", "fr": "Acides forts",
 "pt": "Ácidos fortes", "zh": "强酸"},
"Chlorinated hydrocarbons": {"de": "Chlorierte Kohlenwasserstoffe", "es": "Hidrocarburos clorados",
 "fr": "Hydrocarbures chlorés", "pt": "Hidrocarbonetos clorados", "zh": "氯化烃"},
"Brake fluid (glycol-based)": {"de": "Bremsflüssigkeit (auf Glykolbasis)",
 "es": "Líquido de frenos (a base de glicol)", "fr": "Liquide de frein (à base de glycol)",
 "pt": "Líquido de travões (à base de glicol)", "zh": "刹车油（乙二醇型）"},
"Hydrochloric acid (any concentration)": {"de": "Salzsäure (jede Konzentration)",
 "es": "Ácido clorhídrico (cualquier concentración)", "fr": "Acide chlorhydrique (toute concentration)",
 "pt": "Ácido clorídrico (qualquer concentração)", "zh": "盐酸（任何浓度）"},
"Hot concentrated sulfuric acid": {"de": "Heiße konzentrierte Schwefelsäure",
 "es": "Ácido sulfúrico concentrado caliente", "fr": "Acide sulfurique concentré chaud",
 "pt": "Ácido sulfúrico concentrado a quente", "zh": "热的浓硫酸"},
"Ferric chloride solutions": {"de": "Eisen(III)-chloridlösungen", "es": "Soluciones de cloruro férrico",
 "fr": "Solutions de chlorure ferrique", "pt": "Soluções de cloreto férrico", "zh": "氯化铁溶液"},
"Bleach / sodium hypochlorite": {"de": "Bleiche / Natriumhypochlorit",
 "es": "Lejía / hipoclorito de sodio", "fr": "Eau de Javel / hypochlorite de sodium",
 "pt": "Lixívia / hipoclorito de sódio", "zh": "漂白剂/次氯酸钠"},
"Seawater at elevated temperatures": {"de": "Meerwasser bei erhöhten Temperaturen",
 "es": "Agua de mar a temperaturas elevadas", "fr": "Eau de mer à températures élevées",
 "pt": "Água do mar a temperaturas elevadas", "zh": "高温海水"},
"Reducing acids without oxidizers": {"de": "Reduzierende Säuren ohne Oxidationsmittel",
 "es": "Ácidos reductores sin oxidantes", "fr": "Acides réducteurs sans oxydants",
 "pt": "Ácidos redutores sem oxidantes", "zh": "不含氧化剂的还原性酸"},

# ------------------------------------------------------------- bullet lists
"• Extreme temperatures (-60°C to +230°C)": {"de": "• Extreme Temperaturen (-60 °C bis +230 °C)",
 "es": "• Temperaturas extremas (-60 °C a +230 °C)", "fr": "• Températures extrêmes (-60 °C à +230 °C)",
 "pt": "• Temperaturas extremas (-60 °C a +230 °C)", "zh": "• 极端温度（-60°C 至 +230°C）"},
"• Food and beverage contact (FDA)": {"de": "• Lebensmittel- und Getränkekontakt (FDA)",
 "es": "• Contacto con alimentos y bebidas (FDA)", "fr": "• Contact alimentaire et boissons (FDA)",
 "pt": "• Contacto com alimentos e bebidas (FDA)", "zh": "• 食品和饮料接触（FDA）"},
"• Medical/pharmaceutical applications": {"de": "• Medizin-/Pharmaanwendungen",
 "es": "• Aplicaciones médicas/farmacéuticas", "fr": "• Applications médicales/pharmaceutiques",
 "pt": "• Aplicações médicas/farmacêuticas", "zh": "• 医疗/制药应用"},
"• Water and dilute salt solutions": {"de": "• Wasser und verdünnte Salzlösungen",
 "es": "• Agua y soluciones salinas diluidas", "fr": "• Eau et solutions salines diluées",
 "pt": "• Água e soluções salinas diluídas", "zh": "• 水和稀盐溶液"},
"• Ozone and UV exposure": {"de": "• Ozon- und UV-Einwirkung",
 "es": "• Exposición al ozono y a los rayos UV", "fr": "• Exposition à l'ozone et aux UV",
 "pt": "• Exposição a ozono e UV", "zh": "• 臭氧和紫外线暴露"},
"• Electrical insulation": {"de": "• Elektrische Isolierung", "es": "• Aislamiento eléctrico",
 "fr": "• Isolation électrique", "pt": "• Isolamento elétrico", "zh": "• 电气绝缘"},
"• Concentrated acids and bases": {"de": "• Konzentrierte Säuren und Laugen",
 "es": "• Ácidos y bases concentrados", "fr": "• Acides et bases concentrés",
 "pt": "• Ácidos e bases concentrados", "zh": "• 浓酸和浓碱"},
"• Most solvents (acetone, toluene, etc.)": {"de": "• Die meisten Lösemittel (Aceton, Toluol usw.)",
 "es": "• La mayoría de los disolventes (acetona, tolueno, etc.)",
 "fr": "• La plupart des solvants (acétone, toluène, etc.)",
 "pt": "• A maioria dos solventes (acetona, tolueno, etc.)", "zh": "• 大多数溶剂（丙酮、甲苯等）"},
"• Fuels and oils": {"de": "• Kraftstoffe und Öle", "es": "• Combustibles y aceites",
 "fr": "• Carburants et huiles", "pt": "• Combustíveis e óleos", "zh": "• 燃油和油类"},
"• Steam (causes reversion)": {"de": "• Dampf (führt zu Reversion)", "es": "• Vapor (provoca reversión)",
 "fr": "• Vapeur (provoque une réversion)", "pt": "• Vapor (provoca reversão)", "zh": "• 蒸汽（会导致返原）"},
"• Abrasive environments (low tear strength)": {"de": "• Abrasive Umgebungen (geringe Weiterreißfestigkeit)",
 "es": "• Entornos abrasivos (baja resistencia al desgarro)",
 "fr": "• Environnements abrasifs (faible résistance à la déchirure)",
 "pt": "• Ambientes abrasivos (baixa resistência ao rasgamento)", "zh": "• 磨蚀性环境（撕裂强度低）"},
"• Hydrocarbon gases": {"de": "• Kohlenwasserstoffgase", "es": "• Gases de hidrocarburos",
 "fr": "• Gaz d'hydrocarbures", "pt": "• Gases de hidrocarbonetos", "zh": "• 烃类气体"},
"• Fuels (gasoline, diesel, biodiesel)": {"de": "• Kraftstoffe (Benzin, Diesel, Biodiesel)",
 "es": "• Combustibles (gasolina, diésel, biodiésel)", "fr": "• Carburants (essence, gazole, biodiesel)",
 "pt": "• Combustíveis (gasolina, gasóleo, biodiesel)", "zh": "• 燃油（汽油、柴油、生物柴油）"},
"• Oils (motor, hydraulic, silicone)": {"de": "• Öle (Motoren-, Hydraulik-, Silikonöl)",
 "es": "• Aceites (de motor, hidráulicos, de silicona)", "fr": "• Huiles (moteur, hydraulique, silicone)",
 "pt": "• Óleos (de motor, hidráulicos, de silicone)", "zh": "• 油类（机油、液压油、硅油）"},
"• Mineral acids (sulfuric, nitric, phosphoric)": {"de": "• Mineralsäuren (Schwefel-, Salpeter-, Phosphorsäure)",
 "es": "• Ácidos minerales (sulfúrico, nítrico, fosfórico)",
 "fr": "• Acides minéraux (sulfurique, nitrique, phosphorique)",
 "pt": "• Ácidos minerais (sulfúrico, nítrico, fosfórico)", "zh": "• 无机酸（硫酸、硝酸、磷酸）"},
"• Aromatic solvents (toluene, xylene)": {"de": "• Aromatische Lösemittel (Toluol, Xylol)",
 "es": "• Disolventes aromáticos (tolueno, xileno)", "fr": "• Solvants aromatiques (toluène, xylène)",
 "pt": "• Solventes aromáticos (tolueno, xileno)", "zh": "• 芳香族溶剂（甲苯、二甲苯）"},
"• Chlorinated solvents": {"de": "• Chlorierte Lösemittel", "es": "• Disolventes clorados",
 "fr": "• Solvants chlorés", "pt": "• Solventes clorados", "zh": "• 氯化溶剂"},
"• High temperatures (up to 200°C / 392°F)": {"de": "• Hohe Temperaturen (bis 200 °C / 392 °F)",
 "es": "• Altas temperaturas (hasta 200 °C / 392 °F)",
 "fr": "• Températures élevées (jusqu'à 200 °C / 392 °F)",
 "pt": "• Temperaturas elevadas (até 200 °C / 392 °F)", "zh": "• 高温（最高 200°C / 392°F）"},
"• Ketones (acetone, MEK)": {"de": "• Ketone (Aceton, MEK)", "es": "• Cetonas (acetona, MEK)",
 "fr": "• Cétones (acétone, MEK)", "pt": "• Cetonas (acetona, MEK)", "zh": "• 酮类（丙酮、丁酮）"},
"• Esters (ethyl acetate)": {"de": "• Ester (Ethylacetat)", "es": "• Ésteres (acetato de etilo)",
 "fr": "• Esters (acétate d'éthyle)", "pt": "• Ésteres (acetato de etilo)", "zh": "• 酯类（乙酸乙酯）"},
"• Amines and ammonia": {"de": "• Amine und Ammoniak", "es": "• Aminas y amoníaco",
 "fr": "• Amines et ammoniac", "pt": "• Aminas e amoníaco", "zh": "• 胺类和氨"},
"• Low molecular weight organic acids": {"de": "• Organische Säuren mit niedriger Molmasse",
 "es": "• Ácidos orgánicos de bajo peso molecular",
 "fr": "• Acides organiques de faible masse moléculaire",
 "pt": "• Ácidos orgânicos de baixo peso molecular", "zh": "• 低分子量有机酸"},
"• Hot water / steam": {"de": "• Heißwasser / Dampf", "es": "• Agua caliente / vapor",
 "fr": "• Eau chaude / vapeur", "pt": "• Água quente / vapor", "zh": "• 热水/蒸汽"},
"• Brake fluids (glycol-based)": {"de": "• Bremsflüssigkeiten (auf Glykolbasis)",
 "es": "• Líquidos de frenos (a base de glicol)", "fr": "• Liquides de frein (à base de glycol)",
 "pt": "• Líquidos de travões (à base de glicol)", "zh": "• 刹车油（乙二醇型）"},
"Excellent ozone and UV resistance": {"de": "Ausgezeichnete Ozon- und UV-Beständigkeit",
 "es": "Excelente resistencia al ozono y a los rayos UV",
 "fr": "Excellente résistance à l'ozone et aux UV",
 "pt": "Excelente resistência a ozono e UV", "zh": "耐臭氧和紫外线性能优异"},
"Low gas permeability": {"de": "Geringe Gasdurchlässigkeit", "es": "Baja permeabilidad a los gases",
 "fr": "Faible perméabilité aux gaz", "pt": "Baixa permeabilidade a gases", "zh": "气体渗透率低"},

# ------------------------------------------------------------------ tips and links
"For oil and fuel applications, use NBR (Nitrile) or Viton® (FKM) instead.": {
 "de": "Für Öl- und Kraftstoffanwendungen stattdessen NBR (Nitril) oder Viton® (FKM) verwenden.",
 "es": "Para aplicaciones con aceites y combustibles, utilice NBR (nitrilo) o Viton® (FKM) en su lugar.",
 "fr": "Pour les applications huiles et carburants, utilisez plutôt du NBR (nitrile) ou du Viton® (FKM).",
 "pt": "Para aplicações com óleos e combustíveis, utilize antes NBR (nitrilo) ou Viton® (FKM).",
 "zh": "用于油类和燃油场合时，请改用 NBR（丁腈橡胶）或 Viton®（FKM）。"},
"For outdoor applications or ozone exposure, use EPDM instead. For extreme chemicals, consider Viton® (FKM).": {
 "de": "Für Außenanwendungen oder Ozoneinwirkung stattdessen EPDM verwenden. Für extreme Chemikalien Viton® (FKM) in Betracht ziehen.",
 "es": "Para aplicaciones exteriores o exposición al ozono, utilice EPDM. Para productos químicos extremos, considere Viton® (FKM).",
 "fr": "Pour les applications extérieures ou l'exposition à l'ozone, utilisez plutôt de l'EPDM. Pour les produits chimiques extrêmes, envisagez le Viton® (FKM).",
 "pt": "Para aplicações no exterior ou exposição a ozono, utilize antes EPDM. Para produtos químicos extremos, considere Viton® (FKM).",
 "zh": "用于户外或有臭氧暴露的场合时请改用 EPDM；面对极端化学品可考虑 Viton®（FKM）。"},
"For highly aggressive chloride environments, consider upgrading to duplex stainless steel (2205) or super-austenitic grades (904L, 254 SMO).": {
 "de": "Für stark chloridhaltige Umgebungen empfiehlt sich ein Wechsel zu Duplex-Edelstahl (2205) oder superaustenitischen Güten (904L, 254 SMO).",
 "es": "En entornos de cloruros muy agresivos, considere pasar a acero inoxidable dúplex (2205) o a grados superausteníticos (904L, 254 SMO).",
 "fr": "Dans les environnements chlorurés très agressifs, envisagez de passer à un acier inoxydable duplex (2205) ou à des nuances super-austénitiques (904L, 254 SMO).",
 "pt": "Em ambientes de cloretos muito agressivos, considere passar para aço inoxidável duplex (2205) ou graus superausteníticos (904L, 254 SMO).",
 "zh": "在氯化物腐蚀极强的环境中，建议改用双相不锈钢（2205）或超级奥氏体牌号（904L、254 SMO）。"},
"For oils/fuels": {"de": "Für Öle/Kraftstoffe", "es": "Para aceites/combustibles",
 "fr": "Pour huiles/carburants", "pt": "Para óleos/combustíveis", "zh": "适用于油类/燃油"},
"For water/outdoor": {"de": "Für Wasser/Außenbereich", "es": "Para agua/exterior",
 "fr": "Pour eau/extérieur", "pt": "Para água/exterior", "zh": "适用于水/户外"},
"Rigid option": {"de": "Starre Alternative", "es": "Opción rígida", "fr": "Option rigide",
 "pt": "Opção rígida", "zh": "刚性替代材料"},
"Rigid plastic": {"de": "Harter Kunststoff", "es": "Plástico rígido", "fr": "Plastique rigide",
 "pt": "Plástico rígido", "zh": "硬质塑料"},
"Metal option": {"de": "Metall-Alternative", "es": "Opción metálica", "fr": "Option métallique",
 "pt": "Opção metálica", "zh": "金属替代材料"},
"Budget option": {"de": "Günstige Alternative", "es": "Opción económica", "fr": "Option économique",
 "pt": "Opção económica", "zh": "经济型选择"},
"Lined option": {"de": "Ausgekleidete Alternative", "es": "Opción revestida", "fr": "Option revêtue",
 "pt": "Opção revestida", "zh": "内衬式选择"},
"Plastic alternative": {"de": "Kunststoff-Alternative", "es": "Alternativa plástica",
 "fr": "Alternative plastique", "pt": "Alternativa em plástico", "zh": "塑料替代材料"},
"For seals": {"de": "Für Dichtungen", "es": "Para juntas", "fr": "Pour joints",
 "pt": "Para vedantes", "zh": "用于密封件"},

# --------------------------------------------------------------------- footers
"© 2026 ChemicalResistance.org — Free chemical compatibility tool": {
 "de": "© 2026 ChemicalResistance.org — Kostenloses Tool für chemische Verträglichkeit",
 "es": "© 2026 ChemicalResistance.org — Herramienta gratuita de compatibilidad química",
 "fr": "© 2026 ChemicalResistance.org — Outil gratuit de compatibilité chimique",
 "pt": "© 2026 ChemicalResistance.org — Ferramenta gratuita de compatibilidade química",
 "zh": "© 2026 ChemicalResistance.org — 免费化学品兼容性工具"},
"© 2026 ChemicalResistance.org — Free Chemical Compatibility Tool": {
 "de": "© 2026 ChemicalResistance.org — Kostenloses Tool für chemische Verträglichkeit",
 "es": "© 2026 ChemicalResistance.org — Herramienta gratuita de compatibilidad química",
 "fr": "© 2026 ChemicalResistance.org — Outil gratuit de compatibilité chimique",
 "pt": "© 2026 ChemicalResistance.org — Ferramenta gratuita de compatibilidade química",
 "zh": "© 2026 ChemicalResistance.org — 免费化学品兼容性工具"},
"Data sources: Bürkle, INEOS, industry standards": {
 "de": "Datenquellen: Bürkle, INEOS, Industriestandards",
 "es": "Fuentes de datos: Bürkle, INEOS, normas del sector",
 "fr": "Sources des données : Bürkle, INEOS, normes industrielles",
 "pt": "Fontes de dados: Bürkle, INEOS, normas do setor",
 "zh": "数据来源：Bürkle、INEOS、行业标准"},
})


# Per-language leftovers with no English original on the page: mostly Portuguese
# headings the PT -> ZH pass never touched, plus a few odds and ends.
EXTRA_STRINGS = {
"zh": [
    ("Sobre Borracha de Silicone (VMQ)", "关于硅橡胶 (VMQ)"),
    ("Sobre Viton® (FPM/FKM)", "关于 Viton® (FPM/FKM)"),
    ("Quando Usar Silicone", "何时使用 Silicone"),
    ("Quando Usar Viton®", "何时使用 Viton®"),
    ("Propriedades Principais", "主要性能"),
    ("Propriedades do EPDM", "EPDM 性能参数"),
    ("Propriedades do SS 316", "SS 316 性能参数"),
    ("NBR Properties", "NBR 性能参数"),
    ("✅ Excelente Para", "✅ 适用于"),
    ("❌ Evitar Com", "❌ 应避免"),
    ("Processamento de Alimentos", "食品加工"),
    ("Comparar Materiais", "材料对比"),
    ("Exterior/Coberturas", "户外/屋面"),
    ("Vapor e HVAC", "蒸汽与暖通空调"),
    (">Tipo<", ">类型<"),
    (">Temperatura<", ">温度<"),
    (">Tip:<", ">提示：<"),
    ("Tabela de Resistência Química | 1,651+ Químicos Testados",
     "化学品耐受性数据表 | 已测试 1,651+ 种化学品"),
    ("Tabela de Resistência Química | 1,650+ Químicos Testados",
     "化学品耐受性数据表 | 已测试 1,650+ 种化学品"),
    ("Tabela de Resistência Química | Dados Limitados Dispon\\u00edveis",
     "化学品耐受性数据表 | 数据有限"),
    ("Tabela de Resistência Química | Compatibilidade de Borracha Nitrílica",
     "化学品耐受性数据表 | 丁腈橡胶兼容性"),
    ("Tabela de Resistência Química | Guia de Compatibilidade de Borracha",
     "化学品耐受性数据表 | 橡胶兼容性指南"),
    ("Tabela de Resistência Química | SS316 Compatibility",
     "化学品耐受性数据表 | SS316 兼容性"),
    ("Tabela de Resist\\u00eancia Qu\\u00edmica | 1,651+ Qu\\u00edmicos Testados",
     "化学品耐受性数据表 | 已测试 1,651+ 种化学品"),
    ("Tabela de Resist\\u00eancia Qu\\u00edmica | 1,650+ Qu\\u00edmicos Testados",
     "化学品耐受性数据表 | 已测试 1,650+ 种化学品"),
    ("Tabela de Resist\\u00eancia Qu\\u00edmica | Dados Limitados Dispon\\u00edveis",
     "化学品耐受性数据表 | 数据有限"),
    ("Tabela de Resist\\u00eancia Qu\\u00edmica | Compatibilidade de Borracha Nitr\\u00edlica",
     "化学品耐受性数据表 | 丁腈橡胶兼容性"),
    ("Tabela de Resist\\u00eancia Qu\\u00edmica | Guia de Compatibilidade de Borracha",
     "化学品耐受性数据表 | 橡胶兼容性指南"),
    ("Tabela de Resist\\u00eancia Qu\\u00edmica | SS316 Compatibility",
     "化学品耐受性数据表 | SS316 兼容性"),
    ("A\\u00e7o Inoxid\\u00e1vel 316 化学品耐受性数据表", "316 不锈钢 化学品耐受性数据表"),
    ("A\\u00e7o Inoxid\\u00e1vel 304 化学品耐受性数据表", "304 不锈钢 化学品耐受性数据表"),
    ("Viton\\u00ae (FPM) 化学品耐受性数据表", "Viton® (FPM) 化学品耐受性数据表"),
    # zh/index.html material guide cards, still Portuguese
    ("Uso gratuito. Sem necessidade de cadastro.", "免费使用，无需注册。"),
    ("Polietileno de alta densidade", "高密度聚乙烯"),
    (">Polipropileno<", ">聚丙烯<"),
    (">Etileno-Propileno-Dieno<", ">三元乙丙橡胶<"),
    ("Ideal para: Ambientes corrosivos. Melhor que 304 para cloretos.",
     "适用于：腐蚀性环境。在氯化物环境中优于 304。"),
    (">Inox 316 →<", ">SS 316 →<"),
    (">Inox 316<", ">SS 316<"),
    # zh/compare FAQ answer, still Portuguese
    ("A (Excelente) = resistência durável. B (Bom) = resistência limitada, adequado para "
     "contatos de curta duração. C (Regular) = o material pode inchar ou se degradar. "
     "D (Ruim) = o material não é adequado.",
     "A（优秀）= 长期耐受。B（良好）= 耐受性有限，适合短时间接触。"
     "C（尚可）= 材料可能溶胀或降解。D（不推荐）= 材料不适用。"),
],
"fr": [
    # The SDS disclaimer was half-overwritten with Spanish.
    ("Consulte siempre la Fiche de Données de Sécurité completa para información detallada.",
     "Consultez toujours la Fiche de Données de Sécurité complète pour des informations détaillées."),
],
"pt": [
    ("Consulte siempre la Ficha de Dados de Segurança completa para información detallada.",
     "Consulte sempre a Ficha de Dados de Segurança completa para informação detalhada."),
],
"de": [],
"es": [],
}


# The lead paragraph on the HDPE, PP and PTFE pages was localized from the wrong
# source text — all three describe a "high-purity fluoropolymer used in the
# semiconductor and pharmaceutical industries", which is the PVDF blurb. The
# English pages carry the correct copy; these are its translations.
WRONG_LEAD_PARAGRAPHS = {
"High-Density Polyethylene (HDPE)": {
 "en": "HDPE is a widely used thermoplastic for chemical storage tanks, containers, and piping. Excellent resistance to many acids, bases, and solvents at an economical price.",
 "de": "HDPE ist ein weit verbreiteter Thermoplast für Chemikalientanks, Behälter und Rohrleitungen. Ausgezeichnete Beständigkeit gegen viele Säuren, Laugen und Lösemittel zu einem günstigen Preis.",
 "es": "El HDPE es un termoplástico muy utilizado en tanques de almacenamiento de productos químicos, recipientes y tuberías. Excelente resistencia a muchos ácidos, bases y disolventes a un precio económico.",
 "fr": "Le HDPE est un thermoplastique très répandu pour les cuves de stockage de produits chimiques, les récipients et les tuyauteries. Excellente résistance à de nombreux acides, bases et solvants, à un prix économique.",
 "pt": "O HDPE é um termoplástico muito utilizado em tanques de armazenamento de produtos químicos, recipientes e tubagens. Excelente resistência a muitos ácidos, bases e solventes a um preço económico.",
 "zh": "HDPE 是广泛用于化学品储罐、容器和管道的热塑性塑料，对多种酸、碱和溶剂具有优秀的耐受性，且价格经济。"},
"Polypropylene (PP)": {
 "en": "Polypropylene is a versatile, lightweight thermoplastic with excellent chemical resistance to acids and bases. Widely used for chemical tanks, piping, and labware.",
 "de": "Polypropylen ist ein vielseitiger, leichter Thermoplast mit ausgezeichneter Chemikalienbeständigkeit gegenüber Säuren und Laugen. Weit verbreitet für Chemikalientanks, Rohrleitungen und Laborartikel.",
 "es": "El polipropileno es un termoplástico ligero y versátil con excelente resistencia química frente a ácidos y bases. Muy utilizado en tanques químicos, tuberías y material de laboratorio.",
 "fr": "Le polypropylène est un thermoplastique léger et polyvalent offrant une excellente résistance chimique aux acides et aux bases. Très utilisé pour les cuves chimiques, les tuyauteries et la verrerie de laboratoire.",
 "pt": "O polipropileno é um termoplástico leve e versátil com excelente resistência química a ácidos e bases. Muito utilizado em tanques químicos, tubagens e material de laboratório.",
 "zh": "聚丙烯是一种用途广泛的轻质热塑性塑料，对酸和碱具有优秀的化学品耐受性，广泛用于化学品储罐、管道和实验器皿。"},
"Polytetrafluoroethylene (Teflon) (PTFE)": {
 "en": "PTFE (Teflon) is the gold standard for chemical resistance — virtually inert to all chemicals. Used in gaskets, seals, bearings, and linings for the most aggressive media.",
 "de": "PTFE (Teflon) ist der Goldstandard der Chemikalienbeständigkeit – nahezu inert gegenüber allen Chemikalien. Verwendet für Dichtungen, Lager und Auskleidungen bei den aggressivsten Medien.",
 "es": "El PTFE (teflón) es el referente en resistencia química: prácticamente inerte frente a todos los productos químicos. Se utiliza en juntas, sellos, cojinetes y revestimientos para los medios más agresivos.",
 "fr": "Le PTFE (téflon) est la référence absolue en résistance chimique — pratiquement inerte face à tous les produits chimiques. Utilisé pour les joints, garnitures, paliers et revêtements destinés aux milieux les plus agressifs.",
 "pt": "O PTFE (teflon) é a referência em resistência química — praticamente inerte a todos os produtos químicos. Utilizado em juntas, vedantes, chumaceiras e revestimentos para os meios mais agressivos.",
 "zh": "PTFE（特氟龙）是化学品耐受性的标杆材料，对几乎所有化学品都呈惰性，常用于最苛刻介质环境下的垫片、密封件、轴承和衬里。"},
"Polyvinylidene Fluoride (PVDF)": {
 "en": "PVDF is a premium fluoropolymer with excellent chemical resistance, particularly to solvents and halogens. Combines high purity with good mechanical strength.",
 "de": "PVDF ist ein hochwertiges Fluorpolymer mit ausgezeichneter Chemikalienbeständigkeit, insbesondere gegenüber Lösemitteln und Halogenen. Es verbindet hohe Reinheit mit guter mechanischer Festigkeit.",
 "es": "El PVDF es un fluoropolímero de alta gama con excelente resistencia química, en especial frente a disolventes y halógenos. Combina alta pureza con buena resistencia mecánica.",
 "fr": "Le PVDF est un fluoropolymère haut de gamme offrant une excellente résistance chimique, en particulier aux solvants et aux halogènes. Il allie haute pureté et bonne résistance mécanique.",
 "pt": "O PVDF é um fluoropolímero de gama alta com excelente resistência química, em especial a solventes e halogéneos. Combina elevada pureza com boa resistência mecânica.",
 "zh": "PVDF 是一种高端氟聚合物，化学品耐受性优异，尤其耐溶剂和卤素，兼具高纯度与良好的机械强度。"},
}

# The localized text those wrong paragraphs currently carry, per language.
WRONG_LEAD_TEMPLATE = {
 "de": "{name} ist ein hochreines Fluorpolymer mit ausgezeichneter Chemikalienbeständigkeit. Verwendet in der Halbleiter- und Pharmaindustrie.",
 "es": "{name} es un fluoropolímero de alta pureza con excelente resistencia química. Utilizado en las industrias de semiconductores y farmacéutica.",
 "fr": "{name} est un fluoropolymère de haute pureté avec une excellente résistance chimique. Utilisé dans les industries des semi-conducteurs et pharmaceutique.",
 "pt": "{name} é um fluoropolímero de alta pureza com excelente resistência química. Utilizado nas indústrias de semicondutores e farmacêutica.",
 "zh": "{name} 具有优秀的化学品耐受性。广泛应用于半导体和制药行业。",
}


MATERIAL_STRINGS.update({
# ------------------------------------------------- remaining table/UI labels
# Result counter: "Showing <span id=resultCount>0</span> chemicals".
'Showing <span id="resultCount" class="font-semibold text-gray-700">0</span> chemicals': {
 "de": 'Angezeigt: <span id="resultCount" class="font-semibold text-gray-700">0</span> Chemikalien',
 "es": 'Mostrando <span id="resultCount" class="font-semibold text-gray-700">0</span> químicos',
 "fr": 'Affichage de <span id="resultCount" class="font-semibold text-gray-700">0</span> produits chimiques',
 "pt": 'A mostrar <span id="resultCount" class="font-semibold text-gray-700">0</span> produtos químicos',
 "zh": '显示 <span id="resultCount" class="font-semibold text-gray-700">0</span> 种化学品'},
'</span> chemicals': {"de": "</span> Chemikalien", "es": "</span> químicos",
 "fr": "</span> produits chimiques", "pt": "</span> produtos químicos", "zh": "</span> 种化学品"},
">Buna-N, Nitrile<": {"de": ">Buna-N, Nitril<", "es": ">Buna-N, nitrilo<",
 "fr": ">Buna-N, nitrile<", "pt": ">Buna-N, nitrilo<", "zh": ">Buna-N、丁腈橡胶<"},
">Concentration<": {"de": ">Konzentration<", "es": ">Concentración<", "fr": ">Concentration<",
 "pt": ">Concentração<", "zh": ">浓度<"},
">Grade<": {"de": ">Güte<", "es": ">Grado<", "fr": ">Nuance<", "pt": ">Grau<", "zh": ">牌号<"},
">Density<": {"de": ">Dichte<", "es": ">Densidad<", "fr": ">Densité<", "pt": ">Densidade<", "zh": ">密度<"},
">Density:<": {"de": ">Dichte:<", "es": ">Densidad:<", "fr": ">Densité :<", "pt": ">Densidade:<", "zh": ">密度：<"},
">Hardness:<": {"de": ">Härte:<", "es": ">Dureza:<", "fr": ">Dureté :<", "pt": ">Dureza:<", "zh": ">硬度：<"},
">Magnetic<": {"de": ">Magnetisch<", "es": ">Magnético<", "fr": ">Magnétique<",
 "pt": ">Magnético<", "zh": ">磁性<"},
">Weldable<": {"de": ">Schweißbar<", "es": ">Soldable<", "fr": ">Soudable<",
 "pt": ">Soldável<", "zh": ">可焊接性<"},
">Available<": {"de": ">Verfügbar<", "es": ">Disponibles<", "fr": ">Disponibles<",
 "pt": ">Disponíveis<", "zh": ">有供应<"},
">Cost<": {"de": ">Kosten<", "es": ">Coste<", "fr": ">Coût<", "pt": ">Custo<", "zh": ">成本<"},
">Low-Moderate<": {"de": ">Niedrig bis mittel<", "es": ">Bajo-moderado<", "fr": ">Faible à modéré<",
 "pt": ">Baixo a moderado<", "zh": ">低至中等<"},
">Moderate-High<": {"de": ">Mittel bis hoch<", "es": ">Moderado-alto<", "fr": ">Modéré à élevé<",
 "pt": ">Moderado a elevado<", "zh": ">中等至较高<"},
">Universal<": {"de": ">Universell<", "es": ">Universal<", "fr": ">Universel<",
 "pt": ">Universal<", "zh": ">通用<"},
">Elastomer<": {"de": ">Elastomer<", "es": ">Elastómero<", "fr": ">Élastomère<",
 "pt": ">Elastómero<", "zh": ">弹性体<"},
"<strong>Tip:</strong>": {"de": "<strong>Tipp:</strong>", "es": "<strong>Consejo:</strong>",
 "fr": "<strong>Conseil :</strong>", "pt": "<strong>Dica:</strong>", "zh": "<strong>提示：</strong>"},
"NBR Properties": {"de": "NBR-Eigenschaften", "es": "Propiedades del NBR",
 "fr": "Propriétés du NBR", "pt": "Propriedades do NBR", "zh": "NBR 性能参数"},
">Nitrile Butadiene Rubber<": {"de": ">Nitril-Butadien-Kautschuk<",
 "es": ">Caucho de nitrilo-butadieno<", "fr": ">Caoutchouc nitrile-butadiène<",
 "pt": ">Borracha de nitrilo-butadieno<", "zh": ">丁腈橡胶<"},
">Ethylene Propylene Diene Monomer<": {"de": ">Ethylen-Propylen-Dien-Kautschuk<",
 "es": ">Monómero de etileno-propileno-dieno<", "fr": ">Monomère éthylène-propylène-diène<",
 "pt": ">Monómero de etileno-propileno-dieno<", "zh": ">三元乙丙橡胶<"},
"Synthetic rubber (elastomer)": {"de": "Synthesekautschuk (Elastomer)",
 "es": "Caucho sintético (elastómero)", "fr": "Caoutchouc synthétique (élastomère)",
 "pt": "Borracha sintética (elastómero)", "zh": "合成橡胶（弹性体）"},
"150°C (302°F) continuous": {"de": "150 °C (302 °F) dauerhaft", "es": "150 °C (302 °F) en continuo",
 "fr": "150 °C (302 °F) en continu", "pt": "150 °C (302 °F) em contínuo", "zh": "150°C（302°F）连续使用"},
"120°C (248°F) continuous": {"de": "120 °C (248 °F) dauerhaft", "es": "120 °C (248 °F) en continuo",
 "fr": "120 °C (248 °F) en continu", "pt": "120 °C (248 °F) em contínuo", "zh": "120°C（248°F）连续使用"},
"870°C (1600°F) intermittent": {"de": "870 °C (1600 °F) zeitweise",
 "es": "870 °C (1600 °F) intermitente", "fr": "870 °C (1600 °F) en intermittent",
 "pt": "870 °C (1600 °F) intermitente", "zh": "870°C（1600°F）间歇使用"},
">Fuel Systems<": {"de": ">Kraftstoffsysteme<", "es": ">Sistemas de combustible<",
 "fr": ">Circuits de carburant<", "pt": ">Sistemas de combustível<", "zh": ">燃油系统<"},
">Hydraulics<": {"de": ">Hydraulik<", "es": ">Hidráulica<", "fr": ">Hydraulique<",
 "pt": ">Hidráulica<", "zh": ">液压系统<"},
">Automotive<": {"de": ">Kfz-Technik<", "es": ">Automoción<", "fr": ">Automobile<",
 "pt": ">Automóvel<", "zh": ">汽车<"},
">Stainless Steel 316<": {"de": ">Edelstahl 316<", "es": ">Acero Inoxidable 316<",
 "fr": ">Acier Inoxydable 316<", "pt": ">Aço Inoxidável 316<", "zh": ">316 不锈钢<"},
">Silicone rubber<": {"de": ">Silikonkautschuk<", "es": ">Caucho de silicona<",
 "fr": ">Caoutchouc silicone<", "pt": ">Borracha de silicone<", "zh": ">硅橡胶<"},
# Rating legend under the silicone table: "<span ...>A</span> Excellent".
">A</span> Excellent<": {"de": ">A</span> Ausgezeichnet<", "es": ">A</span> Excelente<",
 "fr": ">A</span> Excellent<", "pt": ">A</span> Excelente<", "zh": ">A</span> 优秀<"},
">B</span> Good<": {"de": ">B</span> Gut<", "es": ">B</span> Bueno<",
 "fr": ">B</span> Bon<", "pt": ">B</span> Bom<", "zh": ">B</span> 良好<"},
">C</span> Limited<": {"de": ">C</span> Begrenzt<", "es": ">C</span> Limitado<",
 "fr": ">C</span> Limité<", "pt": ">C</span> Aceitável<", "zh": ">C</span> 尚可<"},
})


import re


def _ws_escape(text):
    """Literal chunk as a regex, with every run of whitespace matching \\s+."""
    return "".join(r"\s+" if not part.strip() else re.escape(part)
                   for part in re.split(r"(\s+)", text) if part)


def _pattern(canonical, partial):
    """Regex matching the canonical English string on disk.

    The original translation pass replaced individual terms in place and left
    the rest of the sentence alone, and it did not do so uniformly: on the ZH
    silicone page "chemical resistance" was translated while "temperature
    range" was not. So each known partial term is matched as "either the
    English or the localized form" rather than committing to one variant.
    """
    marked = canonical
    for idx, (_local, english) in enumerate(partial):
        marked = marked.replace(english, f"\x00{idx}\x01")
    out = []
    for i, chunk in enumerate(re.split(r"\x00(\d+)\x01", marked)):
        if i % 2:
            local, english = partial[int(chunk)]
            out.append(f"(?:{_ws_escape(english)}|{_ws_escape(local)})")
        elif chunk:
            out.append(_ws_escape(chunk))
    return re.compile("".join(out))


def _compile(pairs, partial=()):
    """(pattern, replacement) pairs. The replacement is wrapped in a lambda so
    backslashes in a translation are never read as regex group references."""
    out = []
    for src, dst in pairs:
        if src == dst:
            continue
        out.append((_pattern(src, partial), (lambda d: lambda m: d)(dst)))
    return out


def rules_for(lang):
    """(pattern, replacement) pairs for one language, longest source first."""
    pairs = []
    partial = PARTIAL_TERMS.get(lang, [])
    for canonical, translations in MATERIAL_STRINGS.items():
        pairs.append((canonical, translations[lang]))
    for name, blurbs in WRONG_LEAD_PARAGRAPHS.items():
        pairs.append((WRONG_LEAD_TEMPLATE[lang].format(name=name), blurbs[lang]))
    pairs.sort(key=lambda p: -len(p[0]))
    return _compile(pairs, partial)


def extra_rules(lang):
    """Language-tree-wide leftovers (not restricted to the material pages)."""
    pairs = sorted(EXTRA_STRINGS.get(lang, []), key=lambda p: -len(p[0]))
    return _compile(pairs)
